version: "3.8"
services:
  osfbot:
    container_name: osfbot
    image: ghcr.io/manipal-osf/bot:main
    init: true

    restart: on-failure
    env_file:
      - .env

    environment:
      - ENVIRONMENT=DOCKER-DEVELOPMENT
